### ISSUE TITLE
Version 1 shows as out today, but not showing up in nuget

### ISSUE THREAD

**Issue by RituM24** [Geta/geta-optimizely-categories#13]
Hi

The releases show v 1 was released today, but i can't see it in nuget repo. Thoughts?

**Comment by brianweet** [comment]
It takes a little while before it's available on the opti nuget but it's out now!

https://nuget.optimizely.com/package/?id=Geta.Optimizely.Categories
https://nuget.optimizely.com/package/?id=Geta.Optimizely.Categories.Find
