### ISSUE TITLE
Categories not synchronizing to Optimizely Graph

### ISSUE THREAD

**Issue by dluk** [Geta/geta-optimizely-categories#39]
When synchronizing content to Optimizely Graph categories itself are not synchronized and content links expanded from Graph query are also empty for categories.
Query to graph: 
`query test {
    DetailPage {
        items {
            Categories {
                Id
                Expanded {
                    Name
                    ParentLink {
                        Id
                    }
                }
            }
        }
    }`
 
response from graph:
```
"data": {
	"DetailPage": {
		"items": [
			{
				"Categories": [
					{
						"Id": 29274,
						"Expanded": {
							"Name": null,
							"ParentLink": {
								"Id": null
							}
						}
					}
				]
			}
		]
	}
}
```

After some debugging it appears that Graph content serializer `Optimizely.ContentGraph.Cms.Core.Internal.ContentSerializer` only supports these Base content types:
```
public string[] SupportedContentBaseTypes
{
  get
  {
    return new string[11]
    {
      "Page",
      "Media",
      "Image",
      "Video",
      "Block",
      "Catalog",
      "Node",
      "Product",
      "Variation",
      "Bundle",
      "Package"
    };
  }
}
```
And category types are stored in database table `[dbo].[tblContentType]` with `Base` column as NULL. SQL query:
``` 
SELECT [ModelType]
      ,[Name]
      ,[MetaDataInherit]
      ,[MetaDataDefault]
      ,[ContentType]
      ,[Base]
      ,[Version]
      ,[SupportedMediaExtensions]
      ,[GroupName]
FROM .[dbo].[tblContentType]
WHERE ModelType like 'Geta%'
OR Name = 'SiteCategory'
```

Query result:
![image](https://github.com/Geta/geta-optimizely-categories/assets/2986940/49bb23b5-2c85-4d78-a35a-601af4a9f35f)

Our `SiteCategory` class:
```
[ContentType]
public class SiteCategory : CategoryData
{
	[Display(Name = "Display Text")]
	[CultureSpecific]
	public virtual string DisplayText { get; set; }
}
```
And `Categories` property on `DetailPage` content type:
```
[Display(Name = "Categories")]
[Categories]
public virtual IList<ContentReference> Categories { get; set; }
```

Will this be fixed and is there a workaround to make it synchronize categories to Optimizely Graph?

**Comment by frederikvig** [comment]
Optimizely would need to add support for the `ContentBase` content type in `Optimizely.ContentGraph.Cms.Core.Internal.ContentSerializer`

```
public string[] SupportedContentBaseTypes
{
  get
  {
    return new string[11]
    {
      "Page",
      "Media",
      "Image",
      "Video",
      "Block",
      "Catalog",
      "Node",
      "Product",
      "Variation",
      "Bundle",
      "Package"
    };
  }
}
```

**Comment by frederikvig** [comment]
This has been flagged with the Optimizely Product / Engineering teams.

**Comment by IOSven** [comment]
Hi @frederikvig, 

Upon querying GraphQL with the following query, we notice that the categories are indexed in GraphQL:

```
query MyQuery {
  SearchresultsPage {
    items {
      ResultTypes {
        Id
      }
    }
  }
}
```
Result:
```
"data": {
    "SearchresultsPage": {
      "items": [
        {
          "ResultTypes": [
            {
              "Id": 283
            },
            {
              "Id": 285
            },
            {
              "Id": 286
            }
          ]
        }
      ]
    }
  }
```

We've created a custom category with a property:
`public virtual string? CustomField {get; set;} `
However, this property is not being indexed by Optimizely Graph. 

Is there a specific configuration or attribute required to make custom properties available in GraphQL? Or is there a workaround for this limitation? Thanks in advance for your help!
