### ISSUE TITLE
Release Timelines

### ISSUE THREAD

**Issue by GeekInTheNorth** [Geta/geta-optimizely-categories#5]
Hello Geta,

Do you know when this package will be ready for CMS12 .NET 5/6?  Is assistance required to get this closer toward release?

Regards,
Mark

**Comment by brianweet** [comment]
And it's out! (.NET 5 first)
https://nuget.optimizely.com/package/?id=Geta.Optimizely.Categories
https://nuget.optimizely.com/package/?id=Geta.Optimizely.Categories.Find

**Comment by brianweet** [comment]
@GeekInTheNorth good to hear! 👍 🎉
